modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/MoriyaShiine/hourai-elixir/issues" #optional
[[mods]] #mandatory
modId="houraielixir" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Hourai Elixir" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/hourai-elixir" #optional
credits="cybercat5555 for textures" #optional
authors="MoriyaShiine" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''An (unobtainable) overpowered item that grants immortality'''
[[dependencies.houraielixir]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.houraielixir]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
