modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory
issueTrackerURL="https://github.com/MoriyaShiine/hourai-elixir/issues" #optional
[[mods]] #mandatory
modId="houraielixir" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Hourai Elixir" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/hourai-elixir" #optional
credits="cybercat5555 for textures" #optional
authors="MoriyaShiine" #optional
description='''An (unobtainable) overpowered item that grants immortality'''
[[dependencies.houraielixir]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.houraielixir]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
