modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MoriyaShiine/hourai-elixir/issues"
[[mods]]
modId="houraielixir"
version="${file.jarVersion}"
displayName="Hourai Elixir"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hourai-elixir"
logoFile="icon.png"
authors="MoriyaShiine, cybercat5555"
description='''An (unobtainable) overpowered item that grants immortality'''
[[dependencies.bewitchment]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bewitchment]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
